- homework_create_more_models/README.md
Model comment would not work due to model function "approved" having the same name has the boolean field name. Changed the boolean field name to "approved_comment" and it is now functional.
> Fix-Comment-Model

- authentication_authorization/README.md
- heroku/README.md
- homework/README.md
- homework_create_more_models/README.md
- optional_postgresql_installation/README.md
Added syntax highlighting for code blocks.
> Add syntax highlight

- authentication_authorization/README.md
> updated link to Django Auth system docs

- homework_create_more_models/README.md
a few words seemed to be missing
> Minor edit for clarity

- book.json
Moving to 2.5 and trying to fix #25
> Updating to gitbook 2.5

- .gitignore
- book.json
Add link to github repository to help people contribute.
> Add link to github repository

- optional_postgresql_installation/README.md
> Fixed typo

- homework/README.md
- homework_create_more_models/README.md
Same as https://github.com/DjangoGirls/tutorial/pull/701
> Simplify regex

- homework_create_more_models/README.md
I added a missing import to the comments extension.
Thanks for the great tutorial!
> Added instructions to import login_required decorator

- optional_postgresql_installation/README.md
1. The snippets for creating user and database were confusing to me at first, hence minor changes in the narrative.
2. Also, I wanted it to be more clear that it is a new, clean database, which implies the migrations need to be applied and superuser created.
> Some clearing-up for the PostgreSQL installation

- homework/README.md
posts shouldnt be published with the save button when editing
(perhaps we should include a publish button on edit page)
> remove publish post line from edit_post

- homework/README.md
When you say "we added `{% else %}` line here" you actually hadn't, you had just repeated the {% endif %}, so I fixed it. :)
> Fix the code

- authentication_authorization/README.md
* Use new-style urlpatterns
* remove admin.autodiscover
Fixes #49 and #9
> Update so urls.py looks correct for 1.9

- homework_create_more_models/README.md
since it was imported already in a previous chapter of the tutorial
extensions
Fixes #45
> Remove extra login_required import

- authentication_authorization/README.md
- homework/README.md
I've made a few changes that fix some typos. And also beautified some code :sparkles:
> Fix grammar and typos, beautify code

- optional_postgresql_installation/README.md
Changed Postgres backend engine according to Django 1.10 rules.
> Porting to Django 1.10

- authentication_authorization/README.md
> fixed issue #79

- authentication_authorization/README.md
This is already done at an earlier stage, so instructions have
been adjusted to make sense.
Fixes #44
> Remove instruction for is_authenticated check

- en/README.md
fixes issue #92
This pull request makes the links consistent with those in SUMMARY.md
> Update broken links

- en/README.md
fixes small grammatical error in README.md
> Fix typo in README.md

- en/homework_create_more_models/README.md
Set 'on_delete' parameter as 'models.CASCADE' in models.ForeignKey() to create field 'post'.
> Missing 'on_delete' parameter in models.ForeignKey()

- en/homework/README.md
Hey all!
This PR fixes a raised NameError after one continues the tutorial using django 2, but collides with django 1 syntax used in tutorial-extensions. 
So it fixes issue #108.
Tutorial-extensions needs to be updated anyway to be conform with the django-tutorial.
Regards
Patrik
> Replace url statement with path statement

- en/homework/README.md
There is syntax error inside path() in the section describing deletion of post.
> correction in path() of english for deleting post

- en/authentication_authorization/README.md
* use `path` function instead of `url`
* use `views.LoginView` instead of `views.login` (for Django 2.1.x)
* source code: https://github.com/ftnext/my-first-blog/tree/e379c55423b1fe089cdfbf104013241d98caab38
* my blog(Japanese): http://nikkie-ftnext.hatenablog.com/entry/2018/11/26/232818
The Japanese Django Girls community is translating the extension tutorial.
We noticed that the code for Django 1.x remained, so I propose an update for Django 2.x.
> [security chapter] update code for Django 2.x

- en/homework_create_more_models/README.md
update en/homework_create_more_models 
ref: PR https://github.com/DjangoGirls/tutorial-extensions/pull/119 [security chapter] update code for Django 2.x
* use `path` function instead of `url`
* source code: https://github.com/ftnext/my-first-blog/tree/538cdbd980386937ed71d2632c29d5a72cdcc30d
> [comment chapter] update code for Django 2.x

- en/authentication_authorization/README.md
Thank you for reviewing and merging PR https://github.com/DjangoGirls/tutorial-extensions/pull/119 ([security chapter] update code for Django 2.x).
I noticed that there was a code and link for Django 1.x in the text, so I fixed it for Django 2.x.
I will appreciate your review of this.
* line 38: use `path` function instead of `url` (Sorry, I had overlooked the code in the text)
* line 147: update document link for Django 2.1.x
> [security chapter] update text for Django 2.x

- es/README.md
- es/homework/README.md
- es/homework_create_more_models/README.md
Added support for django2 and translating from #110 to spanish
> [es] Added support for Django 2

- ja/SUMMARY.md
Because the Japanese version of SUMMARY.md was untranslated, I translated to Japanese.
> Translated SUMMARY.md into Japanese

- ko/homework_create_more_models/README.md
Add "on_delete" for a new version of Django.
> Add "on_delete" for Korean version.

- en/heroku/README.md
The previous version on the tutorial was buggy, updated to use most recent version 🎊 🦄
> fix: update psycopg2 version and whitenoise config

- book.json
- package-lock.json
- package.json
Contributors adding to the tutorial-extensions need a way to test their contributions locally before making a pull request. This PR adds Honkit to tutorial-extensions repo.
> Add Honkit to tutorial-extensions to enable local testing

- en/heroku/README.md
> Fix grammar

- ko/README.md
fixed the link for the GitHub page extension
> fixed the link for the extension

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- CNAME
- Makefile
Changes in this PR
- Add Makefile
- Add CNAME for subdomain
> Add CNAME and Makefile

- en/homework/README.md
- en/homework_create_more_models/README.md
- es/homework/README.md
- es/homework_create_more_models/README.md
- ja/homework/README.md
- ja/homework_create_more_models/README.md
- ko/homework/README.md
- ko/homework_create_more_models/README.md
fixes #156
(idea from #169 :heart:)
> put "raw" text outside of quotes

- book.json
Add our new sponsor to sidebar ads
> Add DigitalOcean to sponsor ads
